In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('winequality-red.csv')

In [4]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [12]:
dataset.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [19]:
corr_var=df.corr()
print(corr_var)
plt.figure(figsize=(10,7.5))
sns.heatmap(corr_var, annot=True, cmap='BuPu')

                      fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.256131     0.671703   
volatile acidity          -0.256131          1.000000    -0.552496   
citric acid                0.671703         -0.552496     1.000000   
residual sugar             0.114777          0.001918     0.143577   
chlorides                  0.093705          0.061298     0.203823   
free sulfur dioxide       -0.153794         -0.010504    -0.060978   
total sulfur dioxide      -0.113181          0.076470     0.035533   
density                    0.668047          0.022026     0.364947   
pH                        -0.682978          0.234937    -0.541904   
sulphates                  0.183006         -0.260987     0.312770   
alcohol                   -0.061668         -0.202288     0.109903   
quality                    0.124052         -0.390558     0.226373   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity    

<Axes: >

In [5]:
pip install pandas scikit-learn tensorflow


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 1.6/376.0 MB 8.4 MB/s eta 0:00:45
   ---------------------------------------- 3.9/376.0 MB 9.8 MB/s eta 0:00:39
    --------------------------------------- 6.3/376.0 MB 10.7 MB/s eta 0:00:35
    --------------------------------------- 8.9/376.0 MB 10.9 MB/s eta 0:00:34
   - -------------------------------------- 11.5/376.0 MB 10.9 MB/s eta 0:00:34
   - -------------------------------------- 13.9/376.0 MB 11.0 MB/s eta 0:00:33
   - -------------------------------------- 16.3/376.0 MB 11.1 MB/s eta 0:00:33
   - -------------------------------------- 18.6/376.0 MB 11.0 MB/s eta 0:00:33
   -- ------------------------------------- 20.7/376.0 MB 10.9 MB/s eta 0:00:33
   -- ------------------------------------- 23.1/376.0 MB 11.0 MB/s eta 0:00:33
   -- ------------------------------------- 25.2/376.0 MB

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [7]:
X = df.drop('quality', axis=1)
y = (df['quality'] >= 7).astype(int)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
X_train,X_test

(array([[ 0.21833164,  0.88971201,  0.19209222, ...,  1.09349989,
          0.45822284,  1.12317723],
        [-1.29016623, -1.78878251,  0.65275338, ..., -0.40043872,
         -0.40119696,  1.40827174],
        [ 1.49475291, -0.78434707,  1.01104539, ..., -0.07566946,
          0.51551749, -0.58738978],
        ...,
        [-0.65195559,  0.49909822, -1.08752211, ...,  1.28836145,
         -0.68767023, -0.87248428],
        [-0.24582155, -1.84458448,  0.39683051, ...,  0.05423824,
          0.80199076,  1.40827174],
        [-1.46422367, -1.34236676, -0.06383064, ...,  0.50891521,
         -0.68767023,  2.92877575]]),
 array([[-3.61859850e-01,  1.64286407e-01, -9.85152962e-01, ...,
         -4.65392578e-01, -1.34389336e-04, -7.77452782e-01],
        [-3.03840702e-01, -1.70525408e-01, -5.24491803e-01, ...,
          5.08915214e-01, -1.03143815e+00, -8.72484283e-01],
        [ 1.37871461e+00,  7.78108067e-01, -2.68568937e-01, ...,
         -2.05577167e-01,  1.83329452e+00, -4.92358280e-

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [22]:
model = tf.keras.models.Sequential()

In [23]:
model.add(Dense(units=6, activation='relu',))
model.add(Dense(units=6, activation='relu'))

In [24]:
model.add(Dense(units=1, activation='sigmoid'))

In [25]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [40]:
history=model.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8865 - loss: 0.2719
Epoch 2/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.2513
Epoch 3/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2277
Epoch 4/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8869 - loss: 0.2534
Epoch 5/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8813 - loss: 0.2600
Epoch 6/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8833 - loss: 0.2572
Epoch 7/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8858 - loss: 0.2540
Epoch 8/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8991 - loss: 0.2495
Epoch 9/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8926 - loss: 0.2456
Epoch 10/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8856 - loss: 0.2634
Epoch 11/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8826 - loss: 0.2699
Epoch 12/50
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8986 - lo

In [28]:
y_pred =model.predict(X_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step 


In [29]:
y_pred

array([[1.26311732e-02],
       [1.42601365e-03],
       [3.10788043e-02],
       [8.97483621e-03],
       [4.63587232e-02],
       [4.16301051e-03],
       [1.87654817e-03],
       [7.14353938e-03],
       [1.02157705e-01],
       [6.53005838e-02],
       [4.68348801e-01],
       [1.86946094e-02],
       [3.03573385e-02],
       [4.88911197e-03],
       [1.04798805e-02],
       [4.91452277e-01],
       [4.94130189e-03],
       [3.58725451e-02],
       [6.58891141e-01],
       [1.62101556e-02],
       [2.56428160e-02],
       [4.12054639e-03],
       [1.18831642e-01],
       [5.39992332e-01],
       [1.66576877e-02],
       [2.70959195e-02],
       [3.85228693e-01],
       [2.42606997e-02],
       [2.33599190e-02],
       [3.70998681e-01],
       [6.11981051e-03],
       [1.95388664e-02],
       [6.07091710e-02],
       [1.68890115e-02],
       [2.25484278e-02],
       [1.27493334e-03],
       [3.53964299e-01],
       [2.12609231e-01],
       [1.16311714e-01],
       [1.76368952e-01],


In [30]:
y_pred = (y_pred > 0.5)

In [31]:
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [33]:
y_test_reshaped = y_test.to_numpy().reshape(-1, 1)

In [35]:
y_pred_reshaped = y_pred.reshape(-1, 1)

In [36]:
result = np.concatenate((y_pred_reshaped, y_test_reshaped), axis=1)
print(result)


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test_reshaped, y_pred_reshaped)
print(cm)
accuracy_score(y_test, y_pred)

[[260  13]
 [ 31  16]]


0.8625